# Generated by Django 5.0.6 on 2024-06-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maxsulotlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('narx', models.TextField()),
                ('max_soni', models.TextField()),
                ('min_soni', models.TextField()),
                ('destrib', models.TextField()),
                ('img', models.TextField()),
            ],
        ),
    ]
