# Generated by Django 5.0.6 on 2024-06-01 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maxsulotlar',
            name='img',
            field=models.ImageField(upload_to=''),
        ),
    ]
