# Generated by Django 5.0.6 on 2024-06-01 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_alter_maxsulotlar_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maxsulotlar',
            name='img',
            field=models.ImageField(upload_to='image/'),
        ),
    ]
