# Generated by Django 5.0.6 on 2024-06-01 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_alter_maxsulotlar_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maxsulotlar',
            name='img',
            field=models.TextField(),
        ),
    ]
