# Generated by Django 5.0.6 on 2024-06-03 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_alter_maxsulotlar_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maxsulotlar',
            name='img',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='maxsulotlar',
            name='max_soni',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='maxsulotlar',
            name='min_soni',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='maxsulotlar',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='maxsulotlar',
            name='narx',
            field=models.CharField(max_length=255),
        ),
    ]
