# Generated by Django 5.0.6 on 2024-06-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_alter_maxsulotlar_img_alter_maxsulotlar_max_soni_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maxsulotlar',
            name='sana',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
