# Generated by Django 5.0.6 on 2024-06-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0006_maxsulotlar_sana'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xaridlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('max_name', models.CharField(max_length=255)),
                ('sana', models.CharField(max_length=255)),
                ('narx', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='maxsulotlar',
            name='sana',
        ),
    ]
