# Generated by Django 5.0.6 on 2024-06-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0007_xaridlar_remove_maxsulotlar_sana'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UN', models.CharField(max_length=255)),
                ('PN', models.CharField(max_length=255)),
                ('TS', models.CharField(max_length=255)),
                ('CM', models.CharField(max_length=255)),
                ('P', models.CharField(max_length=255)),
                ('M', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Xaridlar',
        ),
        migrations.RemoveField(
            model_name='maxsulotlar',
            name='max_soni',
        ),
        migrations.RemoveField(
            model_name='maxsulotlar',
            name='min_soni',
        ),
        migrations.RemoveField(
            model_name='maxsulotlar',
            name='narx',
        ),
        migrations.AddField(
            model_name='maxsulotlar',
            name='url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='maxsulotlar',
            name='img',
            field=models.ImageField(upload_to='image/'),
        ),
    ]
